# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('consumption', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.CharField(choices=[('a1', 'area1'), ('a2', 'area2')], max_length=2)),
                ('tariff', models.CharField(choices=[('t1', 'tariff1'), ('t2', 'tariff2'), ('t3', 'tariff3')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='consumption',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User'),
        ),
    ]
